---
Metadata:
  AWSToolsMetrics:
    IaC_Generator: "arn:aws:cloudformation:us-east-2:021923260870:generatedTemplate/e381c7f8-d261-41ea-bafe-6f5eca3ed8fe"
Parameters:
  LambdaFunctionTrabajofinalCodeSourceKMSKeyArn6qchr:
    NoEcho: "true"
    Type: "String"
    Description: "The ARN of the KMSlong (KMS) customer managed key that's used to\
      \ encrypt your function's .zip deployment package. If you don't provide a customer\
      \ managed key, Lambda uses an [owned key](https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html#aws-owned-cmk)."
  LambdaFunctionTrabajofinalCodeImageUriHDtJl:
    NoEcho: "true"
    Type: "String"
    Description: "URI of a [container image](https://docs.aws.amazon.com/lambda/latest/dg/lambda-images.html)\
      \ in the Amazon ECR registry."
  LambdaFunctionTrabajofinalCodeS3ObjectVersionWPBlD:
    NoEcho: "true"
    Type: "String"
    Description: "For versioned objects, the version of the deployment package object\
      \ to use."
  LambdaFunctionTrabajofinalCodeS3KeyXM5Z0:
    NoEcho: "true"
    Type: "String"
    Description: "The Amazon S3 key of the deployment package."
  LambdaFunctionTrabajofinalCodeZipFileiSbys:
    NoEcho: "true"
    Type: "String"
    Description: "(Node.js and Python) The source code of your Lambda function. If\
      \ you include your function source inline with this parameter, CFN places it\
      \ in a file named ``index`` and zips it to create a [deployment package](https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-package.html).\
      \ This zip file cannot exceed 4MB. For the ``Handler`` property, the first part\
      \ of the handler identifier must be ``index``. For example, ``index.handler``.\n\
      \  When you specify source code inline for a Node.js function, the ``index``\
      \ file that CFN creates uses the extension ``.js``. This means that Node.js\
      \ treats the file as a CommonJS module.\n When using Node.js 24 or later, Node.js\
      \ can automatically detect if a ``.js`` file should be treated as CommonJS or\
      \ as an ES module. To enable auto-detection, add the ``--experimental-detect-module``\
      \ flag to the ``NODE_OPTIONS`` environment variable. For more information, see\
      \ [Experimental Node.js features](https://docs.aws.amazon.com//lambda/latest/dg/lambda-nodejs.html#nodejs-experimental-features).\n\
      \   For JSON, you must escape quotes and special characters such as newline\
      \ (``\\n``) with a backslash.\n If you specify a function that interacts with\
      \ an AWS CloudFormation custom resource, you don't have to write your own functions\
      \ to send responses to the custom resource that invoked the function. AWS CloudFormation\
      \ provides a response module ([cfn-response](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-lambda-function-code-cfnresponsemodule.html))\
      \ that simplifies sending responses. See [Using Lambda with CloudFormation](https://docs.aws.amazon.com/lambda/latest/dg/services-cloudformation.html)\
      \ for details."
  LambdaFunctionTrabajofinalCodeS3Bucket7Mnjx:
    NoEcho: "true"
    Type: "String"
    Description: "An Amazon S3 bucket in the same AWS-Region as your function. The\
      \ bucket can be in a different AWS-account."
Resources:
  CloudFrontDistribution:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::CloudFront::Distribution"
    DeletionPolicy: "Retain"
    Properties:
      DistributionConfig:
        Logging:
          IncludeCookies: false
          Bucket: ""
          Prefix: ""
        Comment: ""
        DefaultRootObject: ""
        Origins:
        - ConnectionTimeout: 10
          OriginAccessControlId: "E37B5QB2ZJK3E8"
          ConnectionAttempts: 3
          OriginCustomHeaders: []
          DomainName: "proyecto-final-1-021923260870-us-east-2-an.s3.us-east-2.amazonaws.com"
          OriginShield:
            Enabled: false
          S3OriginConfig:
            OriginReadTimeout: 30
            OriginAccessIdentity: ""
          OriginPath: ""
          Id: "proyecto-final-1-021923260870-us-east-2-an.s3.us-east-2.amazonaws.com-mo7scvpvyuq"
        ViewerCertificate:
          MinimumProtocolVersion: "TLSv1"
          SslSupportMethod: "vip"
          CloudFrontDefaultCertificate: true
        PriceClass: "PriceClass_All"
        DefaultCacheBehavior:
          Compress: true
          FunctionAssociations: []
          LambdaFunctionAssociations: []
          TargetOriginId: "proyecto-final-1-021923260870-us-east-2-an.s3.us-east-2.amazonaws.com-mo7scvpvyuq"
          ViewerProtocolPolicy: "redirect-to-https"
          GrpcConfig:
            Enabled: false
          TrustedSigners: []
          FieldLevelEncryptionId: ""
          TrustedKeyGroups: []
          AllowedMethods:
          - "HEAD"
          - "GET"
          CachedMethods:
          - "HEAD"
          - "GET"
          SmoothStreaming: false
          CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6"
        Staging: false
        CustomErrorResponses: []
        ContinuousDeploymentPolicyId: ""
        OriginGroups:
          Quantity: 0
          Items: []
        Enabled: true
        Aliases: []
        IPV6Enabled: true
        WebACLId: ""
        HttpVersion: "http2"
        Restrictions:
          GeoRestriction:
            Locations: []
            RestrictionType: "none"
        CacheBehaviors: []
  ApiGatewayV2Api:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::ApiGatewayV2::Api"
    DeletionPolicy: "Retain"
    Properties:
      IpAddressType: "dualstack"
      RouteSelectionExpression: "$request.method $request.path"
      DisableExecuteApiEndpoint: false
      ProtocolType: "HTTP"
      Tags: {}
      Name: "proyecto-final"
  LambdaFunctionTrabajofinal:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::Lambda::Function"
    DeletionPolicy: "Retain"
    Properties:
      MemorySize: 128
      Description: ""
      TracingConfig:
        Mode: "PassThrough"
      Timeout: 3
      RuntimeManagementConfig:
        UpdateRuntimeOn: "Auto"
      Handler: "index.handler"
      Code:
        SourceKMSKeyArn:
          Ref: "LambdaFunctionTrabajofinalCodeSourceKMSKeyArn6qchr"
        S3ObjectVersion:
          Ref: "LambdaFunctionTrabajofinalCodeS3ObjectVersionWPBlD"
        S3Bucket:
          Ref: "LambdaFunctionTrabajofinalCodeS3Bucket7Mnjx"
        ZipFile:
          Ref: "LambdaFunctionTrabajofinalCodeZipFileiSbys"
        ImageUri:
          Ref: "LambdaFunctionTrabajofinalCodeImageUriHDtJl"
        S3Key:
          Ref: "LambdaFunctionTrabajofinalCodeS3KeyXM5Z0"
      Role: "arn:aws:iam::021923260870:role/service-role/trabajo-final-role-dm6zgv1t"
      FileSystemConfigs: []
      FunctionName: "trabajo-final"
      Runtime: "nodejs24.x"
      PackageType: "Zip"
      LoggingConfig:
        LogFormat: "Text"
        LogGroup: "/aws/lambda/trabajo-final"
      RecursiveLoop: "Terminate"
      EphemeralStorage:
        Size: 512
      Architectures:
      - "x86_64"
  DynamoDBTableProyectofinalworkshops:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::DynamoDB::Table"
    DeletionPolicy: "Retain"
    Properties:
      SSESpecification:
        SSEEnabled: false
      TableName: "proyecto-final-workshops"
      AttributeDefinitions:
      - AttributeType: "S"
        AttributeName: "GSI1PK"
      - AttributeType: "S"
        AttributeName: "GSI1SK"
      ContributorInsightsSpecification:
        Enabled: false
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      WarmThroughput:
        ReadUnitsPerSecond: 12000
        WriteUnitsPerSecond: 4000
      KeySchema:
      - KeyType: "HASH"
        AttributeName: "GSI1PK"
      - KeyType: "RANGE"
        AttributeName: "GSI1SK"
      DeletionProtectionEnabled: false
      TableClass: "STANDARD"
      Tags: []
      TimeToLiveSpecification:
        Enabled: false
  EventsEventBusTrabajofinalestudiante:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::Events::EventBus"
    DeletionPolicy: "Retain"
    Properties:
      Tags: []
      Name: "trabajo-final-estudiante"
  S3BucketProyectofinal1021923260870useast2an:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::S3::Bucket"
    DeletionPolicy: "Retain"
    Properties:
      AbacStatus: "Disabled"
      WebsiteConfiguration:
        IndexDocument: "index.html"
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        BlockPublicAcls: true
      BucketName: "proyecto-final-1-021923260870-us-east-2-an"
      OwnershipControls:
        Rules:
        - ObjectOwnership: "BucketOwnerEnforced"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - BucketKeyEnabled: true
          BlockedEncryptionTypes:
            EncryptionType:
            - "SSE-C"
          ServerSideEncryptionByDefault:
            SSEAlgorithm: "AES256"
  CloudFrontOriginAccessControl:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::CloudFront::OriginAccessControl"
    DeletionPolicy: "Retain"
    Properties:
      OriginAccessControlConfig:
        SigningBehavior: "always"
        Description: "Created by CloudFront"
        SigningProtocol: "sigv4"
        OriginAccessControlOriginType: "s3"
        Name: "oac-proyecto-final-1-021923260870-us-east-2-an.s3.us-mo7sd7o887t"
  EventsEventBusDefault:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::Events::EventBus"
    DeletionPolicy: "Retain"
    Properties:
      Tags: []
      Name: "default"
  CloudFrontCachePolicy:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::CloudFront::CachePolicy"
    DeletionPolicy: "Retain"
    Properties:
      CachePolicyConfig:
        Comment: "Policy with caching enabled. Supports Gzip and Brotli compression."
        MinTTL: 1
        MaxTTL: 3.1536E7
        ParametersInCacheKeyAndForwardedToOrigin:
          QueryStringsConfig:
            QueryStringBehavior: "none"
          EnableAcceptEncodingBrotli: true
          HeadersConfig:
            HeaderBehavior: "none"
          CookiesConfig:
            CookieBehavior: "none"
          EnableAcceptEncodingGzip: true
        DefaultTTL: 86400
        Name: "Managed-CachingOptimized"
  EventsEventBusTrabajofinaldelete:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::Events::EventBus"
    DeletionPolicy: "Retain"
    Properties:
      Tags: []
      Name: "trabajo-final-delete"
